name: release

on:
  push:
    branches: [master]
  workflow_dispatch:
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
      - "yarn.lock"
      - ".github/"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: yarn && yarn build

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          version-file: ./package.json

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing on https://xpclinks.directchezmoi.com/
        uses: wei/curl@master
        with:
          args: ${{ secrets.JU_CURL_PUBLISH }}

      - name: Publishing on Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bookmarks-cms"
          heroku_email: "julienfroidefond@gmail.com"
