name: release

on:
  push:
    branches: [master]
  workflow_dispatch:
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: yarn && yarn build

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          version-file: ./package.json

      - name: Publishing on https://xpclinks.directchezmoi.com/
        uses: wei/curl@master
        with:
          args: ${{ secrets.JU_CURL_PUBLISH }}

      - name: Publishing on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bookmarks-cms"
          heroku_email: "julienfroidefond@gmail.com"
